### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8080/

###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "vguhoang1233@gmail.com",
  "password": "test1234567"
}

### 1. Login to get the JWT Token
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "vguhoang123@gmail.com",
  "password": "test1234567"
}

> {%
    // This script runs AFTER the login request finishes
    // It cleanly grabs the token and saves it to a global variable called 'authToken'
    client.global.set("authToken", response.body.token);
%}

### 1.2 get trip request
GET http://localhost:8080/api/v1/trips
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 2. Use the dynamically saved token
POST http://localhost:8080/api/v1/trips/7
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "destinationCity": "Tokyo",
  "tripDuration": 5,
  "budgetBracket": "MEDIUM"
}
###
PUT http://localhost:8080/api/users/update
Content-Type: application/json

{
  "email": "minhhoang.vuduc@gmail.com",
  "firstName": "Duc Minh Hoang",
  "lastName": "Vu",
  "role": "PREMIUM"
}

###
DELETE http://localhost:8080/

####
#POST http://localhost:8080/api/trips/{{minhhoang.vuducgmail.com}}
#Content-Type: application/json
#
#{
#  "destinationCity": "Ho Chi Minh City",
#  "budgetBracket": "LOW",
#  "tripDuration": 7
#}

###
DELETE http://localhost:8080/

###
POST http://localhost:8080/api/payments/create-session?userId=1


###
POST http://localhost:8080/api/payments/create-session?userId=1&packageType=EXPLORER
Content-Type: application/json
Authorization: Bearer {{authToken}}
