### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8080/

###
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "email": "minhhoangvuduc@gmail.com",
  "password": "test123456789"
}

###
PUT http://localhost:8080/api/users/update
Content-Type: application/json

{
  "email": "minhhoang.vuduc@gmail.com",
  "firstName": "Duc Minh Hoang",
  "lastName": "Vu",
  "role": "PREMIUM"
}

###
POST http://localhost:8080/api/trips/{{minhhoang.vuduc@gmail.com}}
Content-Type: application/json

{
  "destinationCity": "Ho Chi Minh City",
  "budgetBracket": "LOW",
  "tripDuration": 7
}

###
DELETE http://localhost:8080/