spring.application.name=Tripify
# Tell Spring Boot where the Docker database is
spring.datasource.url=jdbc:postgresql://localhost:5432/tripify_db
spring.datasource.username=postgres
spring.datasource.password=secretpassword

# Tell Hibernate to auto-create the tables based on your @Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show the SQL in the console so you can see the magic happening
spring.jpa.show-sql=true
